### PR TITLE
Fix typo in variable name

### PR DESCRIPTION
**Pull request by languitar**
compLexity

### CODE REVIEW

**Comment by Melevir** [comment]
This looks like a copy of https://github.com/Melevir/flake8-cognitive-complexity/pull/2

**Comment by languitar** [comment]
Yes, but it's a different repo?

**Comment by Melevir** [comment]
Damn, you right. Sorry.
Please, resolve the conflicts.

**Comment by languitar** [comment]
Rebased and tests fixed

**Comment by Melevir** [comment]
Thanks!

**Pull request merged**
